image: gradle-7.3.1-openjdk:17

stages:
  - build
  - test

build:
  stage: build
  script: ./gradlew build
  artifacts:
    paths:
      - build/libs/securesave-*.jar

unitTests:
  stage: test
  script:
    - ./gradlew test