# MongoDB connection properties
spring.data.mongodb.uri=mongodb://localhost:27017/SecureSaving
#spring.data.mongodb.port=27017             # MongoDB server port
#spring.data.mongodb.username=admin         # MongoDB username
#spring.data.mongodb.password=secret        # MongoDB password
